# Generated by Django 4.2.21 on 2025-06-04 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_tutorial_options_project_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='feeling',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('tired', 'Tired'), ('loved', 'Loved'), ('angry', 'Angry')], max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.blogpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
